/*
Ability event list:

onMultiHitCount (skill link)

EOT: Nightmare, Curse, Trapping
onResidualDamage (magic guard)

EOT- End of Turn
2.1- EOT_onWeatherDamage
5- EOT_onStatusRestore (shed skin, healer, hydration)
9.1- EOT_onStatusDamage (poison heal)
14.- EOT_onPassiveEffect (speed boost, harvest, bad dreams, moody)
16- EOT_onFormChange (zen mode)

*/

var Abilitydex = [
{name:"Cacophony",desc:"Gives immunity to Sound.",inbattle:"%u is unaffected."},
{name:"Stench",desc:"May cause flinching.",inbattle:""},
{name:"Drizzle",desc:"Begins a rainstorm.",inbattle:"%u makes it rain!"},
{name:"Speed Boost",desc:"Raises Speed every turn.",inbattle:""},
{name:"Battle Armor",desc:"Protects the user from Critical Hits",inbattle:""},
{name:"Sturdy",desc:"Survives 1-hit KO attacks.",inbattle:"%u holds on!"},
{name:"Damp",desc:"Prevents self-destructing.",inbattle:"%u prevents self-destructing."},
{name:"Limber",desc:"Protects the user from Paralysis.",inbattle:"%u is protected from Paralysis."},
{name:"Sand Veil",desc:"Raises the user's Evasion in the sand.",inbattle:""},
{name:"Static",desc:"Paralyzes foes that contact the user.",inbattle:""},
{name:"Volt Absorb",desc:"Heals when targeted with electricity.",inbattle:"%u restores HP."},
{name:"Water Absorb",desc:"Heals when targeted with water.",inbattle:"%u restores HP."},
{name:"Oblivious",desc:"Prevents infatuation.",inbattle:"%u is protected from infatuation."},
{name:"Cloud Nine",desc:"Suppresses weather conditions.",inbattle:"Effects of the weather disappear."},
{name:"Compound Eyes",desc:"Increases the user's Accuracy.",inbattle:""},
{name:"Insomnia",desc:"Protects the user from Sleep.",inbattle:"%u is protected Sleep."},
{name:"Color Change",desc:"User's type becomes the moves that target it.",inbattle:"%u's Color Change makes it %t."},
{name:"Immunity",desc:"Protects the user from Poison.",inbattle:"%u is protected from Poison."},
{name:"Flash Fire",desc:"Powers up Fire-type moves when hit by one.",inbattle:"%u's Flash Fire boosts its Fire-type moves!"},
{name:"Shield Dust",desc:"Protects the user from added effects of moves.",inbattle:"%u is protected from further effects by Shield Dust."},
{name:"Own Tempo",desc:"Protects the user from Confusion.",inbattle:"%u is protected from Confusion."},
{name:"Suction Cups",desc:"Protects the user from being forced out.",inbattle:"%u is protected from phazing."},
{name:"Intimidate",desc:"Lowers opposing Pokemon's Attack.",inbattle:"%u's Intimidate lowers %f's Attack."},
{name:"Shadow Tag",desc:"Prevents escape from Ghosts.",inbattle:"%u's Shadow Tag prevents Escape."},
{name:"Rough Skin",desc:"Hurts foes that make contact with the user.",inbattle:"%f is hurt by Rough Skin."},
{name:"Wonder Guard",desc:"Only super-effective attacks hit the user.",inbattle:"%u is unaffected."},
{name:"Levitate",desc:"Protects the user from Ground-based moves.",inbattle:""},
{name:"Effect Spore",desc:"May Paralyze, Poison, or put to Sleep on contact.",inbattle:""},
{name:"Synchronize",desc:"Passes status afflictions to their sources.",inbattle:"%u passes its status to %f."},
{name:"Clear Body",desc:"Protects the user from stat drops.",inbattle:"%u's stats are not dropped."},
{name:"Natural Cure",desc:"Heals the user's status when switching.",inbattle:""},
{name:"Lightning Rod",desc:"Draws in electricity and raises Special Attack when it does.",inbattle:"%u's Lightning Rod raises its Special Attack."},
{name:"Serene Grace",desc:"Improves chances of added effects.",inbattle:""},
{name:"Swift Swim",desc:"Raises Speed in the Rian.",inbattle:""},
{name:"Chlorophyll",desc:"Raises Speed in the Sun.",inbattle:""},
{name:"Illuminate",desc:"Attracts wild Pokemon.",inbattle:""},
{name:"Trace",desc:"Copies the foe's ability.",inbattle:"%u copies %f's ability."},
{name:"Huge Power",desc:"Doubles the user's Attack.",inbattle:""},
{name:"Poison Point",desc:"Poisons foes that contact the user.",inbattle:""},
{name:"Inner Focus",desc:"Protects the user from Flinching.",inbattle:"%u is protected from Flinching."},
{name:"Magma Armor",desc:"Protects the user from Freezing.",inbattle:"%u is protected from Freezing."},
{name:"Water Veil",desc:"Protects the user from Burns.",inbattle:"%u is protected from Burning."},
{name:"Magnet Pull",desc:"Prevents Steel-type Pokemon from escaping.",inbattle:"%f can't escape."},
{name:"Soundproof",desc:"Protects the user from sound-based moves.",inbattle:"%u is unaffected."},
{name:"Rain Dish",desc:"Restores the user's HP in the Rain.",inbattle:"%u's health is restored."},
{name:"Sand Stream",desc:"Begins a sandstorm.",inbattle:"%u stirs up a sandstorm."},
{name:"Pressure",desc:"Doubles PP usage of foes.",inbattle:"%u applies its Pressure."},
{name:"Thick Fat",desc:"Gives the user resistence to Fire and Ice.",inbattle:""},
{name:"Early Bird",desc:"Wakes the user up early.",inbattle:""},
{name:"Flame Body",desc:"Burns foes that contact the user.",inbattle:""},
{name:"Run Away",desc:"Allows the user to escape traps.",inbattle:"%u flees."},
{name:"Keen Eye",desc:"Protects the user from Accuracy drops.",inbattle:"%u's Accuracy is not dropped."},
{name:"Hyper Cutter",desc:"Protects the user from Attack drops.",inbattle:"%u's Attack is not dropped."},
{name:"Pickup",desc:"User finds sometimes dropped items.",inbattle:"%u looks around and finds a %i."},
{name:"Truant",desc:"The user only moves half of the time.",inbattle:"%u is loafing around."},
{name:"Hustle",desc:"Raises Attack but lowers Accuracy",inbattle:""},
{name:"Cute Charm",desc:"May infatuate foes on contact.",inbattle:"%f falls in love with %u!"},
{name:"Plus",desc:"",inbattle:""},
{name:"Minus",desc:"",inbattle:""},
{name:"Forecast",desc:"Transforms with the weather.",inbattle:"%u changes forms!"},
{name:"Sticky Hold",desc:"The user's item cannot be removed",inbattle:"%u's item is unaffected."},
{name:"Shed Skin",desc:"May restore the user's status.",inbattle:"%u shed its skin."},
{name:"Guts",desc:"Raises Attack when the user has a status affliction.",inbattle:""},
{name:"Marvel Scale",desc:"Raises Defense when the user has a status affliction.",inbattle:""},
{name:"Liquid Ooze",desc:"Hurts foes that drain the user's health.",inbattle:"%f is hurt by Liquid Ooze."},
{name:"Overgrow",desc:"Powers up Grass-type moves in a pinch.",inbattle:""},
{name:"Blaze",desc:"Powers up Fire-type moves in a pinch.",inbattle:""},
{name:"Torrent",desc:"Powers up Water-type moves in a pinch.",inbattle:""},
{name:"Swarm",desc:"Powers up Bug-type moves in a pinch.",inbattle:""},
{name:"Rock Head",desc:"Protects the user from recoil damage.",inbattle:""},
{name:"Drought",desc:"Begins harsh sunlight.",inbattle:"%u intensified the sun's rays."},
{name:"Arena Trap",desc:"Prevents grounded Pokemon from fleeing.",inbattle:"%u's Arena Trap prevents escape!"},
{name:"Vital Spirit",desc:"Protects the user from Sleep.",inbattle:"%u is protected from Sleep."},
{name:"White Smoke",desc:"Protects the user from stat drops.",inbattle:"%u's stats were not dropped."},
{name:"Pure Power",desc:"Raises the user's Attack.",inbattle:""},
{name:"Shell Armor",desc:"Protects the user from Critical Hits.",inbattle:""},
{name:"Air Lock",desc:"Suppresses weather conditions.",inbattle:"Effects of the weather disappeared."},
{name:"Tangled Feet",desc:"Raises Evasion if confused.",inbattle:""},
{name:"Motor Drive",desc:"Raises Speed if hit by Electricity.",inbattle:""},
{name:"Rivalry",desc:"Raises power of moves against the same gender.",inbattle:""},
{name:"Steadfast",desc:"Raises Speed upon flinching.",inbattle:""},
{name:"Snow Cloak",desc:"Raises Evasion in the Hail.",inbattle:""},
{name:"Gluttony",desc:"The user may eat its berry early.",inbattle:"%u eats its berry early."},
{name:"Anger Point",desc:"Maximizes attack when hit by a Critical hit.",inbattle:""},
{name:"Unburden",desc:"Raises Speed when consuming its held item.",inbattle:""},
{name:"Heatproof",desc:"Gives the user resistance to Fire.",inbattle:""},
{name:"Simple",desc:"Stat changes are more drastic.",inbattle:""},
{name:"Dry Skin",desc:"Heals around Water but hurts around Fire.",inbattle:"%u's Dry Skin %a it."},
{name:"Download",desc:"Boosts the stat the foe is weaker to.",inbattle:""},
{name:"Iron Fist",desc:"Boosts the power of punching moves.",inbattle:""},
{name:"Poison Heal",desc:"Heals the user if poisoned.",inbattle:"%u is restored."},
{name:"Adaptability",desc:"Boosts attacks of the user's type.",inbattle:""},
{name:"Skill Link",desc:"Multi-hit attacks strike maximally.",inbattle:"",
    onMultiHitCount : function () {
        return 5;
    }
},
{name:"Hydration",desc:"Heals status afflictions in the Rain.",inbattle:"%u's Hydration cures it."},
{name:"Solar Power",desc:"Boosts Special Attack but hurts the user in the Sun.",inbattle:"%u loses HP in the sunlight."},
{name:"Quick Feet",desc:"Boosts Speed if the user has a status affliction.",inbattle:""},
{name:"Normalize",desc:"All moves are Normal-type.",inbattle:""},
{name:"Sniper",desc:"Powers up Critical Hits.",inbattle:""},
{name:"Magic Guard",desc:"The user cannot be hurt except by attacks.",inbattle:""},
{name:"No Guard",desc:"Attacks of the user and foe always land.",inbattle:""},
{name:"Stall",desc:"The user moves slower.",inbattle:""},
{name:"Technician",desc:"Boosts the power of weaker moves.",inbattle:""},
{name:"Leaf Guard",desc:"Protects the user from Status in the Sun.",inbattle:"%u is protected from status."},
{name:"Klutz",desc:"User can't use held items.",inbattle:""},
{name:"Mold Breaker",desc:"Abilities cannot stop the user.",inbattle:"%u breaks the mold."},
{name:"Super Luck",desc:"Raises the user's Critical Hit ratio.",inbattle:""},
{name:"Aftermath",desc:"Hurts the Pokemon that faints the user.",inbattle:"%f was hurt by Aftermath."},
{name:"Anticipation",desc:"Senses the foe's super-effective moves.",inbattle:"%u shudders."},
{name:"Forewarn",desc:"Determines the moves known by the foe.",inbattle:"%u is alerted of %f's %m."},
{name:"Unaware",desc:"Ignores the foe's stat changes.",inbattle:""},
{name:"Tinted Lens",desc:"Powers up not-very-effective moves.",inbattle:""},
{name:"Filter",desc:"Powers down super-effective moves.",inbattle:""},
{name:"Slow Start",desc:"The user's Attack and Speed are halved at first.",inbattle:""},
{name:"Scrappy",desc:"Ignores Ghost's immunities.",inbattle:""},
{name:"Storm Drain",desc:"Draws in Water and raises Special Attack when it does.",inbattle:""},
{name:"Ice Body",desc:"Heals the user in the Hail.",inbattle:"%u's health is restored."},
{name:"Solid Rock",desc:"Powers down super-effective moves.",inbattle:""},
{name:"Snow Warning",desc:"Begins a hailstorm.",inbattle:"%u makes it hail."},
{name:"Honey Gather",desc:"May gather Honey.",inbattle:""},
{name:"Frisk",desc:"Checks the foe's item.",inbattle:"%u frisks %f and finds one %i."},
{name:"Reckless",desc:"Powers up moves that cause recoil.",inbattle:""},
{name:"Multitype",desc:"Changes the user's Type to match its Plate.",inbattle:""},
{name:"Flower Gift",desc:"Boosts the party's Attack and Special Defense in the sun.",inbattle:"%u changes form!"},
{name:"Bad Dreams",desc:"Hurts sleeping foes.",inbattle:"%f is having bad dreams."},
{name:"Pickpocket",desc:"May steal the foe's item.",inbattle:"%u stole %f's %i."},
{name:"Sheer Force",desc:"Ignores added effects of moves to boost their power.",inbattle:""},
{name:"Contrary",desc:"Reverses stat changes.",inbattle:""},
{name:"Unnerve",desc:"Prevents foes from eating berries.",inbattle:"%u's unnerve makes its foes nervous."},
{name:"Defiant",desc:"Sharply raises Attack upon having a stat dropped.",inbattle:""},
{name:"Defeatist",desc:"Halves Attack and Special Attack when HP gets low.",inbattle:""},
{name:"Cursed Body",desc:"May disable the foe's move.",inbattle:"%u's Cursed Body disables %f's %m."},
{name:"Healer",desc:"May cure allies' status afflictions.",inbattle:""},
{name:"Friend Guard",desc:"Decreases damage inflicted by allies.",inbattle:""},
{name:"Weak Armor",desc:"Raises Speed and lowers Defense when hit.",inbattle:""},
{name:"Heavy Metal",desc:"Makes the user heavier.",inbattle:""},
{name:"Light Metal",desc:"Makes the user lighter.",inbattle:""},
{name:"Multiscale",desc:"Weakens damage taken from full health.",inbattle:""},
{name:"Toxic Boost",desc:"Raises Attack when Poisoned.",inbattle:""},
{name:"Flare Boost",desc:"Raises Special Attack when Burned.",inbattle:""},
{name:"Harvest",desc:"The user may gather used berries.",inbattle:"%u harvested one %i."},
{name:"Telepathy",desc:"Protects the user from friendly damage.",inbattle:""},
{name:"Moody",desc:"Lowers one stat and sharply raises another every turn.",inbattle:""},
{name:"Overcoat",desc:"Protects the user from Powder moves.",inbattle:"%u is unaffected."},
{name:"Poison Touch",desc:"May poison foes it touches.",inbattle:""},
{name:"Regenerator",desc:"Heals the user when switching out.",inbattle:""},
{name:"Big Pecks",desc:"Protects the user from Defense drops.",inbattle:"%u's Defense is not lowered."},
{name:"Sand Rush",desc:"Boosts Speed in the sand.",inbattle:""},
{name:"Wonder Skin",desc:"May evade moves that cause status afflictions.",inbattle:""},
{name:"Analytic",desc:"Powers up moves when moving last.",inbattle:""},
{name:"Illusion",desc:"The user appears to be another Pokemon.",inbattle:""},
{name:"Imposter",desc:"The user transforms into its foe.",inbattle:""},
{name:"Infiltrator",desc:"Ignores substitutes.",inbattle:""},
{name:"Mummy",desc:"Changes the foe's ability to Mummy on contact.",inbattle:""},
{name:"Moxie",desc:"Raises Attack when landing a knock out.",inbattle:""},
{name:"Justified",desc:"Raises Attack when hit by a Dark-type move.",inbattle:""},
{name:"Rattled",desc:"Raises Speed when hit by a Dark- or Bug-type move.",inbattle:""},
{name:"Magic Bounce",desc:"Reflects Status moves.",inbattle:""},
{name:"Sap Sipper",desc:"Draws in Grass and raises Attack when it does.",inbattle:""},
{name:"Prankster",desc:"Gives priority to Status moves.",inbattle:""},
{name:"Sand Force",desc:"Raises Attack in a Sandstorm.",inbattle:""},
{name:"Iron Barbs",desc:"Hurts foes on contact.",inbattle:"%u is hurt by Iron Barbs"},
{name:"Zen Mode",desc:"Changes from when health is low.",inbattle:""},
{name:"Victory Star",desc:"Increases Accuracy of allies.",inbattle:""},
{name:"Turboblaze",desc:"Abilities cannot stop the user.",inbattle:""},
{name:"Teravolt",desc:"Abilities cannot stop the user.",inbattle:""},
{name:"Aroma Veil",desc:"Protects users from move-limiting attacks.",inbattle:""},
{name:"Flower Veil",desc:"Protects Grass-type Pokemon from stat drops.",inbattle:"%u's Flower Veil prevents the stat drop."},
{name:"Cheek Pouch",desc:"Restores HP when eating a berry.",inbattle:""},
{name:"Protean",desc:"Changes the user's type to match its attack.",inbattle:"%u became %t-type."},
{name:"Fur Coat",desc:"Raises Defense.",inbattle:""},
{name:"Magician",desc:"May steal the foe's item.",inbattle:"%u stole %f's %i."},
{name:"Bulletproof",desc:"Protects from Bullets, Balls, and Bombs.",inbattle:"%u is unaffected."},
{name:"Competitive",desc:"Sharply raises Special Attack upon having a stat dropped.",inbattle:""},
{name:"Strong Jaw",desc:"Boosts the power of biting moves.",inbattle:""},
{name:"Refrigerate",desc:"Turns Normal moves into Ice and powers them up.",inbattle:""},
{name:"Sweet Veil",desc:"Protects its team from Sleep.",inbattle:"%u is protected from Sleep."},
{name:"Stance Change",desc:"Changes the user's form based on its moves.",inbattle:"%u changes into its %f form."},
{name:"Gale Wings",desc:"Gives priority to Flying-type moves.",inbattle:""},
{name:"Mega Launcher",desc:"Powers up Pulse moves.",inbattle:""},
{name:"Grass Pelt",desc:"Boosts Defense in Grassy Terrain.",inbattle:""},
{name:"Symbiosis",desc:"May pass its item to an ally.",inbattle:"%u gaves its item to %f."},
{name:"Tough Claws",desc:"Powers up contact moves.",inbattle:""},
{name:"Pixilate",desc:"Turns Normal moves into Fairy and powers them up.",inbattle:""},
{name:"Gooey",desc:"Slows down foes that make contact.",inbattle:""},
{name:"Aerilate",desc:"Turns Normal moves into Flying and powers them up.",inbattle:""},
{name:"Parental Bond",desc:"The user moves twice per turn.",inbattle:""},
{name:"Dark Aura",desc:"Boosts the power of Dark moves.",inbattle:"%u emits a Dark Aura."},
{name:"Fairy Aura",desc:"Boosts the power of Fairy moves.",inbattle:"%u emits a Fairy Aura."},
{name:"Aura Break",desc:"Reverses the effects of other Auras.",inbattle:"%u reverses all auras."},
{name:"Primordial Sea",desc:"Causes harsh rain.",inbattle:"A harsh rainstorm began."},
{name:"Desolate Land",desc:"Causes intense sun.",inbattle:"A harsh sunlight began."},
{name:"Delta Stream",desc:"Overrides all weather and gives resistence to Flying Pokemon.",inbattle:"Intense winds flled the area."}
];